language: node_js

jobs:
  include:
    - stage: test
      os: linux
      dist: xenial
      node_js: "10"
      addons:
        apt:
          packages:
            - libncurses-dev
            - flex
            - bison
            - gperf
    - os: osx
      osx_image: xcode11
      node_js: "10"

install:
  - yarn
  # FIXME: Install pip packages since they're not cached by Travis CI.
  - pip install --user -r firmware/deps/esp32/esp-idf/requirements.txt

script:
  - yarn build
  - yarn test
  - DISABLE_SPINNER=y ./makestack build --app-dir examples/blink --board esp32

cache:
  yarn: true
  pip: true
  directories:
    - firmware/deps

notifications:
  on_success: change
  on_failure: change
